Repository bashfire/prow-config, pull requests merged in 2020-08, with the labels that each got.

#28 Add a periodic echo job
  config/jobs/bashfire/prow-config.yaml
Labels: lgtm, size/S

#29 Add deployment manifests for k8s-gsm-tools
  config/prow/cluster/k8sgsmtools-config.yaml
  config/prow/cluster/k8sgsmtools-namespace.yaml
  config/prow/cluster/k8sgsmtools-rbac.yaml
  config/prow/cluster/secretrotator-deployment.yaml
  config/prow/cluster/secretsynccontroller-deployment.yaml
Labels: lgtm, ok-to-test, size/L

#30 Modify manifests for k8s-gsm-tools
  config/prow/cluster/secretrotator-deployment.yaml
  config/prow/cluster/secretsynccontroller-deployment.yaml
Labels: lgtm, ok-to-test, size/XS

#31 Enable auto deletion of keys
  config/prow/cluster/secretrotator-deployment.yaml
Labels: lgtm
